# Generated by Django 5.2.7 on 2026-05-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('no_info', 'Не бажаю вказувати')], max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='actor_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('production_date', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('trailer_url', models.URLField(blank=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='film_site_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('no info', 'Не бажаю вказувати ')], max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='pofile_avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('liked_film', models.ManyToManyField(blank=True, related_name='liked_by', to='film_site_app.film')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='film_site_app.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='film_site_app.film')),
            ],
        ),
    ]
