# Generated by Django 5.2.7 on 2026-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='film_posters/'),
        ),
    ]
