# Generated by Django 6.0.5 on 2026-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site_app', '0002_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('no info', 'Не бажаю вказувати')], default='no info', max_length=20, null=True),
        ),
    ]
